"""
Import WHX Dubai 2026 exhibitor data into Event Scout.

Usage:
    python import_exhibitors.py

This script contains curated exhibitor data for the World Health Expo (WHX) Dubai 2026
and imports it via the Event Scout API.
"""

import json
import requests
import sys

# Configuration
API_BASE = "https://event-scout-production.up.railway.app"
API_KEY = "OGibuBdW6KP52UMTpv8g46Zs37g47d9SGv4w21W-o6s"

# WHX Dubai 2026 Exhibitor Data
# Event: Feb 9-13, 2026, Dubai Exhibition Centre
# Categories: Medical Devices, Pharmaceuticals, Health IT, Hospital Equipment,
#             Wellness & Nutrition, Laboratory, Diagnostics, Telemedicine,
#             Healthcare Furniture, Infection Control, Rehabilitation

EXHIBITORS = [
    # --- Medical Devices ---
    {"name": "Medtronic", "booth": "A1-120", "hall": "Hall 1", "category": "Medical Devices", "subcategory": "Surgical & Cardiac", "country": "USA", "website": "https://www.medtronic.com", "description": "Global leader in medical technology - cardiac devices, surgical tools, diabetes management, and neuromodulation therapies.", "products": ["Pacemakers", "Insulin Pumps", "Surgical Navigation", "Spinal Implants"], "tags": ["cardiac", "diabetes", "surgery", "implants"]},
    {"name": "Siemens Healthineers", "booth": "A1-200", "hall": "Hall 1", "category": "Medical Devices", "subcategory": "Imaging & Diagnostics", "country": "Germany", "website": "https://www.siemens-healthineers.com", "description": "Pioneering breakthroughs in healthcare. Imaging, diagnostics, and advanced therapies.", "products": ["MRI Systems", "CT Scanners", "Ultrasound", "Laboratory Diagnostics"], "tags": ["imaging", "diagnostics", "radiology", "AI"]},
    {"name": "Philips Healthcare", "booth": "A1-300", "hall": "Hall 1", "category": "Medical Devices", "subcategory": "Patient Monitoring & Imaging", "country": "Netherlands", "website": "https://www.philips.com/healthcare", "description": "Health technology company focused on improving people's health through meaningful innovation.", "products": ["Patient Monitors", "Ultrasound Systems", "Defibrillators", "Sleep Solutions"], "tags": ["monitoring", "imaging", "connected care", "sleep"]},
    {"name": "GE HealthCare", "booth": "A1-400", "hall": "Hall 1", "category": "Medical Devices", "subcategory": "Imaging & Ultrasound", "country": "USA", "website": "https://www.gehealthcare.com", "description": "Leading global medical technology and digital solutions innovator.", "products": ["CT Scanners", "MRI", "Ultrasound", "AI Analytics"], "tags": ["imaging", "AI", "digital health", "diagnostics"]},
    {"name": "Stryker", "booth": "A2-110", "hall": "Hall 2", "category": "Medical Devices", "subcategory": "Orthopedics & Surgical", "country": "USA", "website": "https://www.stryker.com", "description": "Medical technologies including orthopedic implants, surgical equipment, and neurotechnology.", "products": ["Joint Replacements", "Surgical Equipment", "Hospital Beds", "Navigation Systems"], "tags": ["orthopedics", "surgery", "robotics", "implants"]},
    {"name": "Smith+Nephew", "booth": "A2-130", "hall": "Hall 2", "category": "Medical Devices", "subcategory": "Wound Care & Orthopedics", "country": "UK", "website": "https://www.smith-nephew.com", "description": "Global medical technology company specializing in orthopedics, sports medicine, and wound management.", "products": ["Wound Dressings", "Joint Replacements", "Arthroscopy", "Negative Pressure Therapy"], "tags": ["wound care", "orthopedics", "sports medicine"]},
    {"name": "B. Braun", "booth": "A2-200", "hall": "Hall 2", "category": "Medical Devices", "subcategory": "Infusion & Surgical", "country": "Germany", "website": "https://www.bbraun.com", "description": "Healthcare solutions including infusion therapy, pain management, and surgical instruments.", "products": ["IV Solutions", "Infusion Pumps", "Surgical Instruments", "Wound Closure"], "tags": ["infusion", "surgery", "pain management"]},
    {"name": "Boston Scientific", "booth": "A2-310", "hall": "Hall 2", "category": "Medical Devices", "subcategory": "Interventional Medicine", "country": "USA", "website": "https://www.bostonscientific.com", "description": "Innovative medical solutions for interventional procedures.", "products": ["Stents", "Pacemakers", "Endoscopy Devices", "Neuromodulation"], "tags": ["cardiology", "endoscopy", "urology", "neuromodulation"]},
    {"name": "Olympus Medical", "booth": "A2-400", "hall": "Hall 2", "category": "Medical Devices", "subcategory": "Endoscopy", "country": "Japan", "website": "https://www.olympus-global.com", "description": "World leader in endoscopy systems and minimally invasive surgical solutions.", "products": ["Endoscopes", "Surgical Energy Devices", "Cameras", "Image Systems"], "tags": ["endoscopy", "minimally invasive", "imaging"]},
    {"name": "Becton Dickinson (BD)", "booth": "A3-100", "hall": "Hall 3", "category": "Medical Devices", "subcategory": "Injection & Diagnostics", "country": "USA", "website": "https://www.bd.com", "description": "Global medical technology company advancing the world of health with diagnostics, medical devices, and instruments.", "products": ["Syringes", "Blood Collection", "Diagnostic Instruments", "Medication Management"], "tags": ["diagnostics", "injection", "blood collection"]},

    # --- Pharmaceuticals ---
    {"name": "Pfizer", "booth": "B1-100", "hall": "Hall 3", "category": "Pharmaceuticals", "subcategory": "Vaccines & Therapeutics", "country": "USA", "website": "https://www.pfizer.com", "description": "Global pharmaceutical corporation delivering breakthrough therapies and vaccines.", "products": ["Vaccines", "Oncology", "Rare Disease", "Anti-Infectives"], "tags": ["vaccines", "oncology", "pharma", "rare disease"]},
    {"name": "Roche", "booth": "B1-200", "hall": "Hall 3", "category": "Pharmaceuticals", "subcategory": "Diagnostics & Oncology", "country": "Switzerland", "website": "https://www.roche.com", "description": "Global pioneer in pharmaceuticals and diagnostics focused on advancing science.", "products": ["Cancer Treatments", "Immunology", "Diagnostics", "Personalized Medicine"], "tags": ["oncology", "diagnostics", "immunology", "personalized medicine"]},
    {"name": "Novartis", "booth": "B1-300", "hall": "Hall 3", "category": "Pharmaceuticals", "subcategory": "Innovative Medicines", "country": "Switzerland", "website": "https://www.novartis.com", "description": "Reimagining medicine to improve and extend people's lives.", "products": ["Cardiovascular", "Ophthalmology", "Immunology", "Gene Therapy"], "tags": ["gene therapy", "cardiovascular", "ophthalmology"]},
    {"name": "AstraZeneca", "booth": "B1-400", "hall": "Hall 3", "category": "Pharmaceuticals", "subcategory": "Oncology & Respiratory", "country": "UK", "website": "https://www.astrazeneca.com", "description": "Science-led biopharmaceutical company focusing on the discovery and commercialization of prescription medicines.", "products": ["Oncology", "Respiratory", "Cardiovascular", "Vaccines"], "tags": ["oncology", "respiratory", "biopharmaceuticals"]},
    {"name": "Julphar (Gulf Pharmaceutical Industries)", "booth": "B2-100", "hall": "Hall 3", "category": "Pharmaceuticals", "subcategory": "Generic Pharmaceuticals", "country": "UAE", "website": "https://www.julphar.net", "description": "One of the largest pharmaceutical manufacturers in the Middle East.", "products": ["Generic Medicines", "Insulin", "Cardiovascular", "Anti-Infectives"], "tags": ["generics", "insulin", "MENA", "manufacturing"]},
    {"name": "Neopharma", "booth": "B2-200", "hall": "Hall 3", "category": "Pharmaceuticals", "subcategory": "UAE Pharma Manufacturing", "country": "UAE", "website": "https://www.neopharma.com", "description": "UAE-based pharmaceutical company manufacturing a wide range of medicines.", "products": ["Oncology", "Anti-Infectives", "Cardiovascular", "Nutraceuticals"], "tags": ["UAE", "manufacturing", "oncology"]},
    {"name": "Sanofi", "booth": "B2-300", "hall": "Hall 3", "category": "Pharmaceuticals", "subcategory": "Vaccines & Specialty Care", "country": "France", "website": "https://www.sanofi.com", "description": "Global healthcare leader focusing on patients' needs.", "products": ["Vaccines", "Rare Diseases", "Immunology", "Diabetes"], "tags": ["vaccines", "immunology", "diabetes", "rare disease"]},

    # --- Health IT & Digital Health ---
    {"name": "InterSystems", "booth": "C1-100", "hall": "Hall 4", "category": "Health IT", "subcategory": "Health Data Platform", "country": "USA", "website": "https://www.intersystems.com", "description": "Leading provider of health information systems and data platforms.", "products": ["HealthShare", "IRIS for Health", "TrakCare EHR", "Health Data Analytics"], "tags": ["EHR", "interoperability", "data platform", "analytics"]},
    {"name": "Epic Systems", "booth": "C1-150", "hall": "Hall 4", "category": "Health IT", "subcategory": "Electronic Health Records", "country": "USA", "website": "https://www.epic.com", "description": "Making healthcare software to help people get well, help people stay well.", "products": ["Epic EHR", "MyChart Patient Portal", "Care Everywhere", "Healthy Planet"], "tags": ["EHR", "patient portal", "population health"]},
    {"name": "Cerner (Oracle Health)", "booth": "C1-200", "hall": "Hall 4", "category": "Health IT", "subcategory": "Clinical & Financial Solutions", "country": "USA", "website": "https://www.oracle.com/health", "description": "Cloud-based health IT solutions for hospitals and health systems.", "products": ["Millennium EHR", "Revenue Cycle", "Population Health", "AI Clinical Tools"], "tags": ["EHR", "cloud", "AI", "revenue cycle"]},
    {"name": "Infor Healthcare", "booth": "C1-300", "hall": "Hall 4", "category": "Health IT", "subcategory": "Enterprise Software", "country": "USA", "website": "https://www.infor.com/industries/healthcare", "description": "Enterprise software solutions for healthcare operations.", "products": ["ERP for Healthcare", "Supply Chain", "HR Management", "Financial Planning"], "tags": ["ERP", "supply chain", "operations"]},
    {"name": "Curefit Health", "booth": "C2-100", "hall": "Hall 4", "category": "Health IT", "subcategory": "Digital Wellness", "country": "India", "website": "https://www.curefit.com", "description": "Digital health and fitness platform integrating technology with wellness.", "products": ["Fitness App", "Mental Wellness", "Nutrition Planning", "Health Monitoring"], "tags": ["wellness", "fitness", "digital health", "app"]},
    {"name": "Vezeeta", "booth": "C2-150", "hall": "Hall 4", "category": "Health IT", "subcategory": "Telehealth Platform", "country": "Egypt", "website": "https://www.vezeeta.com", "description": "MENA's leading healthcare booking and telehealth platform.", "products": ["Doctor Booking", "Telehealth", "E-Pharmacy", "Health Records"], "tags": ["telehealth", "booking", "MENA", "e-pharmacy"]},
    {"name": "Nabta Health", "booth": "C2-200", "hall": "Hall 4", "category": "Health IT", "subcategory": "Women's Health Tech", "country": "UAE", "website": "https://www.nabtahealth.com", "description": "AI-powered women's health platform based in the UAE.", "products": ["Health Assessments", "At-Home Testing", "Telehealth", "AI Diagnostics"], "tags": ["women's health", "AI", "UAE", "telehealth"]},

    # --- Hospital Equipment & Infrastructure ---
    {"name": "Hill-Rom (Baxter)", "booth": "D1-100", "hall": "Hall 5", "category": "Hospital Equipment", "subcategory": "Patient Care & Beds", "country": "USA", "website": "https://www.hillrom.com", "description": "Medical technologies for the acute and post-acute care settings.", "products": ["Hospital Beds", "Patient Lifts", "Surgical Tables", "Respiratory Care"], "tags": ["beds", "patient care", "respiratory", "mobility"]},
    {"name": "Getinge", "booth": "D1-200", "hall": "Hall 5", "category": "Hospital Equipment", "subcategory": "Surgical & Sterile", "country": "Sweden", "website": "https://www.getinge.com", "description": "Life-saving technologies for operating rooms, ICUs, and sterilization departments.", "products": ["Surgical Workflows", "Ventilators", "Sterilizers", "Heart-Lung Machines"], "tags": ["surgery", "ICU", "sterilization", "ventilation"]},
    {"name": "Dräger", "booth": "D1-300", "hall": "Hall 5", "category": "Hospital Equipment", "subcategory": "Anesthesia & Ventilation", "country": "Germany", "website": "https://www.draeger.com", "description": "Technology for Life - medical and safety technology.", "products": ["Anesthesia Machines", "Ventilators", "Patient Monitoring", "Gas Detection"], "tags": ["anesthesia", "ventilation", "monitoring", "safety"]},
    {"name": "Steris", "booth": "D1-400", "hall": "Hall 5", "category": "Hospital Equipment", "subcategory": "Sterilization & Infection Prevention", "country": "USA", "website": "https://www.steris.com", "description": "Leading provider of infection prevention and surgical solutions.", "products": ["Sterilizers", "Washer-Disinfectors", "Surgical Tables", "OR Integration"], "tags": ["sterilization", "infection prevention", "surgical"]},
    {"name": "Midmark", "booth": "D2-100", "hall": "Hall 5", "category": "Hospital Equipment", "subcategory": "Exam Room Solutions", "country": "USA", "website": "https://www.midmark.com", "description": "Clinical environment design and medical equipment solutions.", "products": ["Exam Tables", "Dental Equipment", "Digital Diagnostics", "Clinical Workflow"], "tags": ["exam rooms", "dental", "workflow"]},

    # --- Laboratory & Diagnostics ---
    {"name": "Abbott Diagnostics", "booth": "E1-100", "hall": "Hall 6", "category": "Laboratory & Diagnostics", "subcategory": "In Vitro Diagnostics", "country": "USA", "website": "https://www.abbott.com", "description": "Global healthcare company creating breakthrough diagnostics, medical devices, nutrition and medicines.", "products": ["Point-of-Care Testing", "Blood Screening", "Molecular Diagnostics", "Immunoassay"], "tags": ["diagnostics", "point-of-care", "molecular", "screening"]},
    {"name": "bioMérieux", "booth": "E1-200", "hall": "Hall 6", "category": "Laboratory & Diagnostics", "subcategory": "Microbiology & Molecular", "country": "France", "website": "https://www.biomerieux.com", "description": "World leader in the field of in vitro diagnostics for clinical and industrial applications.", "products": ["Blood Cultures", "Molecular Biology", "Antibiotic Sensitivity", "Industrial Microbiology"], "tags": ["microbiology", "molecular", "infectious disease"]},
    {"name": "Sysmex Corporation", "booth": "E1-300", "hall": "Hall 6", "category": "Laboratory & Diagnostics", "subcategory": "Hematology & Urinalysis", "country": "Japan", "website": "https://www.sysmex.com", "description": "Leading global manufacturer of hematology and urinalysis analyzers.", "products": ["Hematology Analyzers", "Urinalysis", "Hemostasis", "Flow Cytometry"], "tags": ["hematology", "analyzers", "urinalysis"]},
    {"name": "Beckman Coulter", "booth": "E1-400", "hall": "Hall 6", "category": "Laboratory & Diagnostics", "subcategory": "Clinical Chemistry", "country": "USA", "website": "https://www.beckmancoulter.com", "description": "Diagnostics company advancing healthcare through laboratory automation.", "products": ["Chemistry Analyzers", "Immunoassay", "Centrifuges", "Flow Cytometry"], "tags": ["chemistry", "automation", "immunoassay"]},

    # --- Wellness, Nutrition & Preventive Health ---
    {"name": "Herbalife Nutrition", "booth": "F1-100", "hall": "Hall 7", "category": "Wellness & Nutrition", "subcategory": "Nutritional Products", "country": "USA", "website": "https://www.herbalife.com", "description": "Global nutrition company with products for weight management, targeted nutrition, and energy.", "products": ["Protein Shakes", "Supplements", "Weight Management", "Sports Nutrition"], "tags": ["nutrition", "supplements", "weight management"]},
    {"name": "Nestlé Health Science", "booth": "F1-200", "hall": "Hall 7", "category": "Wellness & Nutrition", "subcategory": "Medical Nutrition", "country": "Switzerland", "website": "https://www.nestlehealthscience.com", "description": "Advancing the role of nutritional therapy for better health outcomes.", "products": ["Medical Nutrition", "Vitamins", "GI Health", "Pediatric Nutrition"], "tags": ["medical nutrition", "vitamins", "GI health"]},
    {"name": "Aster DM Healthcare", "booth": "F1-300", "hall": "Hall 7", "category": "Wellness & Nutrition", "subcategory": "Healthcare Services", "country": "UAE", "website": "https://www.asterdmhealthcare.com", "description": "Integrated healthcare service provider with hospitals, clinics, and pharmacies across the GCC.", "products": ["Hospital Services", "Clinics", "Pharmacy Chain", "Diagnostics"], "tags": ["healthcare services", "hospitals", "UAE", "GCC"]},
    {"name": "NMC Healthcare", "booth": "F1-400", "hall": "Hall 7", "category": "Wellness & Nutrition", "subcategory": "Healthcare Provider", "country": "UAE", "website": "https://www.nmc.ae", "description": "One of the largest private healthcare operators in the UAE.", "products": ["Hospital Services", "Fertility", "Cosmetic Surgery", "Home Healthcare"], "tags": ["healthcare provider", "UAE", "fertility"]},

    # --- Telemedicine & Remote Care ---
    {"name": "Teladoc Health", "booth": "C3-100", "hall": "Hall 4", "category": "Telemedicine", "subcategory": "Virtual Care Platform", "country": "USA", "website": "https://www.teladochealth.com", "description": "Global leader in whole-person virtual care.", "products": ["Virtual Visits", "Chronic Care Management", "Mental Health", "Expert Medical Opinions"], "tags": ["telehealth", "virtual care", "chronic care", "mental health"]},
    {"name": "Babylon Health", "booth": "C3-200", "hall": "Hall 4", "category": "Telemedicine", "subcategory": "AI-Powered Health", "country": "UK", "website": "https://www.babylonhealth.com", "description": "AI-powered healthcare platform providing accessible and affordable health services.", "products": ["AI Symptom Checker", "Virtual Consultations", "Health Monitoring", "Care Plans"], "tags": ["AI", "symptom checker", "virtual care"]},
    {"name": "Okadoc", "booth": "C3-300", "hall": "Hall 4", "category": "Telemedicine", "subcategory": "Healthcare Scheduling", "country": "UAE", "website": "https://www.okadoc.com", "description": "UAE-based healthcare booking and engagement platform.", "products": ["Doctor Booking", "Queue Management", "Patient Engagement", "Analytics"], "tags": ["booking", "UAE", "patient engagement"]},

    # --- Infection Control & Safety ---
    {"name": "3M Healthcare", "booth": "D2-200", "hall": "Hall 5", "category": "Infection Control", "subcategory": "PPE & Sterilization", "country": "USA", "website": "https://www.3m.com/healthcare", "description": "Science-applied to life. Infection prevention, drug delivery, and health information systems.", "products": ["N95 Respirators", "Surgical Tapes", "Sterilization Products", "Skin Antiseptics"], "tags": ["PPE", "infection prevention", "sterilization"]},
    {"name": "Ecolab", "booth": "D2-300", "hall": "Hall 5", "category": "Infection Control", "subcategory": "Hygiene & Disinfection", "country": "USA", "website": "https://www.ecolab.com", "description": "Global leader in water, hygiene, and infection prevention solutions.", "products": ["Hand Hygiene", "Surface Disinfection", "Water Treatment", "Instrument Reprocessing"], "tags": ["hygiene", "disinfection", "water treatment"]},
    {"name": "Diversey", "booth": "D2-400", "hall": "Hall 5", "category": "Infection Control", "subcategory": "Cleaning & Hygiene", "country": "USA", "website": "https://www.diversey.com", "description": "Cleaning and hygiene solutions for healthcare facilities.", "products": ["Floor Care", "Hand Hygiene", "Laundry Solutions", "Dosing Systems"], "tags": ["cleaning", "hygiene", "healthcare facilities"]},

    # --- Rehabilitation & Assistive Technology ---
    {"name": "Ottobock", "booth": "G1-100", "hall": "Hall 8", "category": "Rehabilitation", "subcategory": "Prosthetics & Orthotics", "country": "Germany", "website": "https://www.ottobock.com", "description": "World's leading manufacturer of prosthetics, orthotics, and wheelchair solutions.", "products": ["Prosthetic Limbs", "Orthotic Devices", "Wheelchairs", "Exoskeletons"], "tags": ["prosthetics", "orthotics", "mobility", "exoskeletons"]},
    {"name": "Invacare", "booth": "G1-200", "hall": "Hall 8", "category": "Rehabilitation", "subcategory": "Home Medical Equipment", "country": "USA", "website": "https://www.invacare.com", "description": "Leading manufacturer of home and long-term care medical products.", "products": ["Wheelchairs", "Respiratory Products", "Beds", "Walking Aids"], "tags": ["wheelchairs", "respiratory", "home care"]},

    # --- AI & Emerging Health Tech ---
    {"name": "Google Health", "booth": "C4-100", "hall": "Hall 4", "category": "Health IT", "subcategory": "AI in Healthcare", "country": "USA", "website": "https://health.google", "description": "Applying AI and technology to make health information more useful.", "products": ["Med-PaLM AI", "Health API", "Imaging AI", "Search Health"], "tags": ["AI", "machine learning", "health data"]},
    {"name": "NVIDIA Healthcare", "booth": "C4-200", "hall": "Hall 4", "category": "Health IT", "subcategory": "AI Computing Platform", "country": "USA", "website": "https://www.nvidia.com/en-us/healthcare", "description": "Accelerating healthcare with AI computing platforms.", "products": ["Clara Platform", "DGX Systems", "AI Training", "Medical Imaging AI"], "tags": ["AI", "GPU", "imaging", "deep learning"]},
    {"name": "Butterfly Network", "booth": "C4-300", "hall": "Hall 4", "category": "Health IT", "subcategory": "Portable Ultrasound", "country": "USA", "website": "https://www.butterflynetwork.com", "description": "Handheld, whole-body ultrasound powered by AI.", "products": ["Butterfly iQ+", "AI-Guided Ultrasound", "Tele-Ultrasound", "Training Platform"], "tags": ["ultrasound", "portable", "AI", "point-of-care"]},
    {"name": "Aidoc", "booth": "C4-400", "hall": "Hall 4", "category": "Health IT", "subcategory": "Radiology AI", "country": "Israel", "website": "https://www.aidoc.com", "description": "AI-powered radiology solutions for real-time clinical decision support.", "products": ["CT AI Triage", "PE Detection", "Stroke AI", "Spine AI"], "tags": ["radiology", "AI", "triage", "decision support"]},

    # --- Regional / MENA Healthcare ---
    {"name": "Mediclinic Middle East", "booth": "F2-100", "hall": "Hall 7", "category": "Healthcare Services", "subcategory": "Hospital Network", "country": "UAE", "website": "https://www.mediclinic.ae", "description": "International private healthcare group with hospitals and clinics across the UAE.", "products": ["Hospital Services", "Day Surgery", "Specialized Clinics", "Corporate Health"], "tags": ["hospitals", "UAE", "private healthcare"]},
    {"name": "Saudi German Hospital", "booth": "F2-200", "hall": "Hall 7", "category": "Healthcare Services", "subcategory": "Hospital Group", "country": "UAE", "website": "https://www.sghgroup.net", "description": "Leading healthcare group in the Middle East with hospitals across the region.", "products": ["Multi-Specialty Hospitals", "IVF", "Cardiology", "Orthopedics"], "tags": ["hospitals", "MENA", "multi-specialty"]},
    {"name": "RAK Hospital", "booth": "F2-300", "hall": "Hall 7", "category": "Healthcare Services", "subcategory": "Specialty Hospital", "country": "UAE", "website": "https://www.rakhospital.com", "description": "Premier healthcare facility in Ras Al Khaimah offering comprehensive medical services.", "products": ["Surgery", "Diagnostics", "Rehabilitation", "Medical Tourism"], "tags": ["hospital", "UAE", "medical tourism"]},
    {"name": "Seha (Abu Dhabi Health Services)", "booth": "F2-400", "hall": "Hall 7", "category": "Healthcare Services", "subcategory": "Government Healthcare", "country": "UAE", "website": "https://www.seha.ae", "description": "Abu Dhabi's largest healthcare network operating hospitals and clinics.", "products": ["Public Hospitals", "Specialty Centers", "Home Care", "Screening Programs"], "tags": ["government", "Abu Dhabi", "public health"]},
    {"name": "Dubai Health Authority", "booth": "F3-100", "hall": "Hall 7", "category": "Healthcare Services", "subcategory": "Government Health", "country": "UAE", "website": "https://www.dha.gov.ae", "description": "Government authority responsible for healthcare in Dubai.", "products": ["Public Health", "Licensing", "Health Regulation", "Smart Health"], "tags": ["government", "Dubai", "regulation", "smart health"]},

    # --- Medical Imaging Specialists ---
    {"name": "Canon Medical Systems", "booth": "A3-200", "hall": "Hall 1", "category": "Medical Devices", "subcategory": "Diagnostic Imaging", "country": "Japan", "website": "https://global.medical.canon", "description": "Diagnostic imaging solutions that help clinicians make confident decisions.", "products": ["CT Systems", "MRI", "Ultrasound", "X-Ray"], "tags": ["imaging", "CT", "MRI", "ultrasound"]},
    {"name": "Fujifilm Healthcare", "booth": "A3-300", "hall": "Hall 1", "category": "Medical Devices", "subcategory": "Imaging & Endoscopy", "country": "Japan", "website": "https://www.fujifilm.com/healthcare", "description": "Innovative medical systems spanning endoscopy, imaging, and AI.", "products": ["Endoscopy Systems", "Digital X-Ray", "AI Imaging", "PACS"], "tags": ["endoscopy", "x-ray", "AI", "PACS"]},
    {"name": "Hologic", "booth": "A3-400", "hall": "Hall 1", "category": "Medical Devices", "subcategory": "Women's Health Imaging", "country": "USA", "website": "https://www.hologic.com", "description": "Global leader in women's health with advanced diagnostic solutions.", "products": ["3D Mammography", "Cervical Cancer Screening", "Surgical Solutions", "Skeletal Health"], "tags": ["mammography", "women's health", "screening"]},

    # --- Dental & Oral Health ---
    {"name": "Dentsply Sirona", "booth": "G2-100", "hall": "Hall 8", "category": "Dental", "subcategory": "Dental Equipment", "country": "USA", "website": "https://www.dentsplysirona.com", "description": "World's largest manufacturer of professional dental products and technologies.", "products": ["CAD/CAM Systems", "Imaging", "Implants", "Endodontic Instruments"], "tags": ["dental", "implants", "CAD/CAM", "imaging"]},
    {"name": "Align Technology", "booth": "G2-200", "hall": "Hall 8", "category": "Dental", "subcategory": "Clear Aligners", "country": "USA", "website": "https://www.aligntech.com", "description": "Makers of Invisalign clear aligners and iTero intraoral scanners.", "products": ["Invisalign", "iTero Scanner", "Vivera Retainers", "ClinCheck Software"], "tags": ["orthodontics", "clear aligners", "digital dentistry"]},

    # --- Healthcare Construction & Design ---
    {"name": "Perkins&Will Healthcare", "booth": "H1-100", "hall": "Hall 8", "category": "Healthcare Design", "subcategory": "Architecture", "country": "USA", "website": "https://perkinswill.com", "description": "Global architecture firm specializing in healthcare facility design.", "products": ["Hospital Design", "Clinic Design", "Master Planning", "Interior Design"], "tags": ["architecture", "hospital design", "planning"]},

    # --- Supply Chain & Logistics ---
    {"name": "McKesson", "booth": "H1-200", "hall": "Hall 8", "category": "Healthcare Supply Chain", "subcategory": "Distribution", "country": "USA", "website": "https://www.mckesson.com", "description": "Healthcare supply chain management solutions and pharmaceutical distribution.", "products": ["Pharmaceutical Distribution", "Medical Supply", "Analytics", "Automation"], "tags": ["supply chain", "distribution", "pharmacy"]},
    {"name": "Cardinal Health", "booth": "H1-300", "hall": "Hall 8", "category": "Healthcare Supply Chain", "subcategory": "Medical Products Distribution", "country": "USA", "website": "https://www.cardinalhealth.com", "description": "Global integrated healthcare services and products company.", "products": ["Medical Products", "Pharmaceutical Distribution", "Lab Products", "Surgical Products"], "tags": ["supply chain", "distribution", "medical products"]},

    # --- Health Insurance & FinTech ---
    {"name": "Daman (National Health Insurance)", "booth": "F3-200", "hall": "Hall 7", "category": "Health Insurance", "subcategory": "Insurance Provider", "country": "UAE", "website": "https://www.damanhealth.ae", "description": "Largest health insurance provider in Abu Dhabi and the UAE.", "products": ["Health Insurance Plans", "Claims Management", "Provider Network", "Wellness Programs"], "tags": ["insurance", "Abu Dhabi", "UAE", "claims"]},
    {"name": "Dubai Insurance Company", "booth": "F3-300", "hall": "Hall 7", "category": "Health Insurance", "subcategory": "Insurance", "country": "UAE", "website": "https://www.dubaiinsurance.ae", "description": "Major insurance company offering comprehensive health coverage in the UAE.", "products": ["Health Insurance", "Travel Insurance", "Corporate Plans", "Individual Plans"], "tags": ["insurance", "Dubai", "corporate health"]},

    # --- Medical Education & Training ---
    {"name": "Laerdal Medical", "booth": "G3-100", "hall": "Hall 8", "category": "Medical Education", "subcategory": "Simulation Training", "country": "Norway", "website": "https://www.laerdal.com", "description": "Helping save lives through medical simulation and training products.", "products": ["Patient Simulators", "CPR Training", "Resuscitation", "Debriefing Software"], "tags": ["simulation", "training", "CPR", "education"]},
    {"name": "CAE Healthcare", "booth": "G3-200", "hall": "Hall 8", "category": "Medical Education", "subcategory": "Simulation", "country": "Canada", "website": "https://www.cae.com/healthcare", "description": "Advanced patient simulation and surgical simulation training.", "products": ["Patient Simulators", "Surgical Simulation", "Ultrasound Trainers", "VR Training"], "tags": ["simulation", "VR", "surgical training"]},

    # --- Biotech & Life Sciences ---
    {"name": "Thermo Fisher Scientific", "booth": "E2-100", "hall": "Hall 6", "category": "Laboratory & Diagnostics", "subcategory": "Life Science Research", "country": "USA", "website": "https://www.thermofisher.com", "description": "World leader serving science with analytical instruments, reagents, and lab equipment.", "products": ["PCR Systems", "Mass Spectrometry", "Cell Culture", "Genetic Analysis"], "tags": ["life science", "PCR", "genomics", "research"]},
    {"name": "Illumina", "booth": "E2-200", "hall": "Hall 6", "category": "Laboratory & Diagnostics", "subcategory": "Genomics", "country": "USA", "website": "https://www.illumina.com", "description": "Global leader in DNA sequencing and array-based technologies.", "products": ["Gene Sequencers", "Microarrays", "Library Prep", "Informatics"], "tags": ["genomics", "sequencing", "precision medicine"]},

    # --- More Regional Companies ---
    {"name": "Al Futtaim Health", "booth": "F4-100", "hall": "Hall 7", "category": "Healthcare Services", "subcategory": "Retail Healthcare", "country": "UAE", "website": "https://www.alfuttaim.com", "description": "Healthcare division of Al Futtaim Group offering pharmacy and clinic services.", "products": ["Pharmacy Chain", "Clinics", "Health Retail", "Wellness"], "tags": ["pharmacy", "retail", "UAE"]},
    {"name": "Pure Health", "booth": "F4-200", "hall": "Hall 7", "category": "Healthcare Services", "subcategory": "Diagnostic Services", "country": "UAE", "website": "https://www.purehealth.ae", "description": "UAE's largest integrated diagnostics and healthcare platform.", "products": ["Lab Diagnostics", "Radiology", "Pathology", "Genomics"], "tags": ["diagnostics", "UAE", "genomics", "pathology"]},
    {"name": "Omantel Health", "booth": "F4-300", "hall": "Hall 7", "category": "Health IT", "subcategory": "Smart Health Solutions", "country": "Oman", "website": "https://www.omantel.om", "description": "Oman's telecom provider offering smart health and connectivity solutions.", "products": ["IoT Health", "Connectivity", "Cloud Solutions", "Smart Hospital"], "tags": ["smart health", "IoT", "Oman", "connectivity"]},
    {"name": "Bupa Arabia", "booth": "F4-400", "hall": "Hall 7", "category": "Health Insurance", "subcategory": "Insurance Provider", "country": "Saudi Arabia", "website": "https://www.bupa.com.sa", "description": "Leading health insurance company in Saudi Arabia and the GCC.", "products": ["Health Insurance", "Corporate Plans", "Telemedicine", "Wellness Programs"], "tags": ["insurance", "Saudi Arabia", "GCC", "corporate"]},

    # --- Additional Key Exhibitors ---
    {"name": "Mindray", "booth": "A4-100", "hall": "Hall 2", "category": "Medical Devices", "subcategory": "Patient Monitoring & Imaging", "country": "China", "website": "https://www.mindray.com", "description": "Global medical device manufacturer specializing in patient monitoring, imaging, and IVD.", "products": ["Patient Monitors", "Ultrasound", "Anesthesia Machines", "Lab Analyzers"], "tags": ["monitoring", "ultrasound", "anesthesia", "IVD"]},
    {"name": "Nihon Kohden", "booth": "A4-200", "hall": "Hall 2", "category": "Medical Devices", "subcategory": "Monitoring & Diagnostics", "country": "Japan", "website": "https://www.nihonkohden.com", "description": "Leading manufacturer of medical electronic equipment.", "products": ["EEG", "ECG", "Patient Monitors", "Defibrillators"], "tags": ["EEG", "ECG", "monitoring", "neurology"]},
    {"name": "Masimo", "booth": "A4-300", "hall": "Hall 2", "category": "Medical Devices", "subcategory": "Non-Invasive Monitoring", "country": "USA", "website": "https://www.masimo.com", "description": "Global medical technology company developing noninvasive monitoring technologies.", "products": ["Pulse Oximetry", "Brain Monitoring", "Capnography", "Hospital Automation"], "tags": ["pulse oximetry", "monitoring", "non-invasive"]},
    {"name": "Zimmer Biomet", "booth": "A4-400", "hall": "Hall 2", "category": "Medical Devices", "subcategory": "Musculoskeletal", "country": "USA", "website": "https://www.zimmerbiomet.com", "description": "Global leader in musculoskeletal healthcare with surgical and digital solutions.", "products": ["Knee Implants", "Hip Implants", "Spine Solutions", "Robotic Surgery"], "tags": ["orthopedics", "implants", "robotics", "spine"]},
    {"name": "Baxter International", "booth": "D3-100", "hall": "Hall 5", "category": "Hospital Equipment", "subcategory": "Renal & Hospital Products", "country": "USA", "website": "https://www.baxter.com", "description": "Global healthcare company with products for kidney disease, hospital products, and surgical care.", "products": ["Dialysis", "IV Solutions", "Nutrition Products", "Surgical Hemostats"], "tags": ["dialysis", "IV", "renal care", "nutrition"]},
    {"name": "Fresenius Medical Care", "booth": "D3-200", "hall": "Hall 5", "category": "Hospital Equipment", "subcategory": "Dialysis & Renal", "country": "Germany", "website": "https://www.freseniusmedicalcare.com", "description": "World's leading provider of products and services for people with renal diseases.", "products": ["Dialysis Machines", "Dialyzers", "Bloodlines", "Renal Pharmaceuticals"], "tags": ["dialysis", "renal", "kidney care"]},
    {"name": "Johnson & Johnson MedTech", "booth": "A5-100", "hall": "Hall 1", "category": "Medical Devices", "subcategory": "Surgical & Vision", "country": "USA", "website": "https://www.jnj.com/medtech", "description": "MedTech division offering surgical solutions, orthopedics, and vision care.", "products": ["Surgical Staplers", "Contact Lenses", "Orthopedic Implants", "Electrophysiology"], "tags": ["surgery", "vision", "orthopedics", "electrophysiology"]},
    {"name": "Medline Industries", "booth": "D3-300", "hall": "Hall 5", "category": "Hospital Equipment", "subcategory": "Medical Supplies", "country": "USA", "website": "https://www.medline.com", "description": "Healthcare company and medical supply distributor.", "products": ["Surgical Supplies", "Gloves", "Wound Care", "Skin Care"], "tags": ["medical supplies", "surgical", "wound care"]},
    {"name": "Omnicell", "booth": "C5-100", "hall": "Hall 4", "category": "Health IT", "subcategory": "Medication Management", "country": "USA", "website": "https://www.omnicell.com", "description": "Medication management automation for hospitals and pharmacies.", "products": ["Automated Dispensing", "IV Compounding", "Medication Adherence", "Analytics"], "tags": ["medication", "automation", "pharmacy", "dispensing"]},
    {"name": "Zebra Technologies Healthcare", "booth": "C5-200", "hall": "Hall 4", "category": "Health IT", "subcategory": "Clinical Mobility", "country": "USA", "website": "https://www.zebra.com/healthcare", "description": "Enterprise mobility and data capture solutions for healthcare.", "products": ["Clinical Smartphones", "RTLS Tracking", "Barcode Scanners", "Wristband Printers"], "tags": ["mobility", "RTLS", "tracking", "clinical"]},
]

def import_to_api():
    """Import exhibitors via the Event Scout API."""
    url = f"{API_BASE}/admin/import_exhibitors/"
    headers = {
        "X-API-Key": API_KEY,
        "Content-Type": "application/json"
    }

    print(f"Importing {len(EXHIBITORS)} exhibitors to {url}...")

    resp = requests.post(url, headers=headers, json={"exhibitors": EXHIBITORS}, timeout=60)

    if resp.status_code == 200:
        data = resp.json()
        print(f"Success! {data}")
    else:
        print(f"Error {resp.status_code}: {resp.text}")

    return resp


def save_to_json(filepath="whx_exhibitors.json"):
    """Save exhibitor data to a JSON file."""
    with open(filepath, "w") as f:
        json.dump({"exhibitors": EXHIBITORS}, f, indent=2)
    print(f"Saved {len(EXHIBITORS)} exhibitors to {filepath}")


if __name__ == "__main__":
    if "--json" in sys.argv:
        save_to_json()
    else:
        import_to_api()
